### ISSUE TITLE
Error when processing Sentinel-2 L1C data with the tool

### ISSUE THREAD

**Issue by safalabolo** [Evoland-Land-Monitoring-Evolution/sentinel2_superresolution#14]
Dear maintainers,

I encountered an issue while using the tool to process Sentinel-2 L1C data. After running the tool with the specified data, I received the following error message:

**Command:**
C:\Users\Utente\Downloads\test2>sentinel2_superesolution -i S2A_MSIL1C_20240908T095031_N0511_R079_T33TVF_20240908T120652.SAFE --l1c -o C:\Users\Utente\Downloads\test2

**Error message:**
Super-resolution in progress ...:   0%|                                                        | 0/484 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python310\Scripts\sentinel2_superesolution.exe\__main__.py", line 7, in <module>
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python310\lib\site-packages\sentinel2_superresolution\run.py", line 454, in run
    main(sys.argv[1:])
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python310\lib\site-packages\sentinel2_superresolution\run.py", line 376, in main
    output = ort_session.run(
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 266, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(double)) , expected: (tensor(float))

Interestingly, when I process the same dataset in MAJA format (Theia), the issue does not occur.

Is there something I might have overlooked?
Thank you for your assistance!
Best regards,

**Comment by jmichel-otb** [comment]
Thanks for reporting this, I will have a look. Did you by any chance recently reinstall your environment ?

**Comment by safalabolo** [comment]
Hi @jmichel-otb, 
Thank you for your reply. 
Yes, I recently reinstalled the tool to account for potential updates. 
The previous version I installed back in May was working correctly with the Sentinel-2 L1C product.
All the best.
safalabolo

**Comment by jmichel-otb** [comment]
Thanks for reporting. A bug had indeed been introduced in recent refactoring of **sensorsio**, ingoring the default requested dtype (float32) and always returning a float64 array.

I just pushed a fix:
https://framagit.org/jmichel-otb/sensorsio/-/commit/e81fda47f07d56942717c0f551872479122e2c28

A fresh re-install of sentinel2_superresolution and dependencies should fix the problem. I personnally do:

```bash
$ conda create -p s2sr_env python==3.11
$ conda activate s2sr_env
$ pip install git+https://framagit.org/jmichel-otb/sentinel2_superresolution.git
```

Let me know if that worked for you.

**Comment by safalabolo** [comment]
Hi @jmichel-otb 

Thank you for the quick fix! I just processed a Sentinel-2 L1C granule, and everything worked perfectly without any errors.

I really appreciate your support and the detailed instructions.

Best regards,
safalabolo
