### ISSUE TITLE
INVALID_PROTOBUF

### ISSUE THREAD

**Issue by safalabolo** [Evoland-Land-Monitoring-Evolution/sentinel2_superresolution#3]
Hi,
I received this error message when I tried to process Sentinel-2 L1C data:

**sentinel2_superesolution -v -i S2B_MSIL1C_20230823T095559_N0509_R122_T33TUG_20230823T121626.SAFE/ --l1c -o out/**

[2024-04-30 10:29:28] INFO:sentinel2_superresolution.run:Will process SENTINEL2B, 2023-08-23 09:55:59, 33TUG
[2024-04-30 10:29:28] INFO:sentinel2_superresolution.run:Bounds: BoundingBox(left=300000.0, bottom=4590240.0, right=409800.0, top=4700040.0), EPSG:32633
[2024-04-30 10:29:28] INFO:sentinel2_superresolution.run:Will use model /root/miniconda3/lib/python3.10/site-packages/sentinel2_superresolution/../../models/carn_3x3x64g4sw_bootstrap.onnx
Traceback (most recent call last):
  File "/usr/local/bin/sentinel2_superesolution", line 8, in <module>
    sys.exit(run())
  File "/root/miniconda3/lib/python3.10/site-packages/sentinel2_superresolution/run.py", line 424, in run
    main(sys.argv[1:])
  File "/root/miniconda3/lib/python3.10/site-packages/sentinel2_superresolution/run.py", line 281, in main
    ort_session = ort.InferenceSession(args.model, sess_options=so, providers=ep_list)
  File "/root/miniconda3/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/root/miniconda3/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /root/miniconda3/lib/python3.10/site-packages/sentinel2_superresolution/../../models/carn_3x3x64g4sw_bootstrap.onnx failed:Protobuf parsing failed.

**Comment by jmichel-otb** [comment]
Packaging and README have been fixed.
